spring:
  datasource:
    url: jdbc:mysql://docker-mysql:3306/learn-oauth2
    username: root
    password: root
server:
  port: 8181
  servlet:
    context-path: /auth-service

debug: false

logging:
  level:
    org:
      springframework:
        security: WARN
