spring:
  datasource:
    platform: all
    url: jdbc:mysql://localhost:3306/learn-oauth2
    username: root
    password: root
server:
  port: 8181
  servlet:
    context-path: /auth-service
debug: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
