version: '3'

services:
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=learn-oauth2
      - MYSQL_PASSWORD=root
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    depends_on:
      - docker-mysql
    links:
      - docker-mysql:docker-mysql
    ports:
      - 8181:8181
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=learn-oauth2
      - DATABASE_PORT=3306
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    depends_on:
      - auth-service
    links:
      - auth-service:auth-service
    ports:
      - 8080:8080
    environment:
      - AUTH_SERVICE_HOST=auth-service
      - AUTH_SERVICE_PORT=8181
  notes-service:
    build:
      context: ./notes-service
      dockerfile: Dockerfile
    depends_on:
      - docker-mysql
      - auth-service
    links:
      - auth-service:auth-service
      - docker-mysql:docker-mysql
    ports:
      - 8182:8182
    environment:
      - AUTH_SERVICE_HOST=auth-service
      - AUTH_SERVICE_PORT=8181
