server:
  servlet:
    context-path: /notes-service
  port: 8182
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://docker-mysql:3306/learn-oauth2
    username: root
    password: root
    initialization-mode: always
security:
  oauth2:
    resource:
      user-info-uri: http://${AUTH_SERVICE_EXT_HOST:192.168.99.100}:8181/auth-service/me
