server:
  servlet:
    context-path: /notes-service
  port: 8182
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/user_notes
    username: root
    password: root
debug: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
